### ISSUE TITLE
Add option to return a copy of data

### ISSUE THREAD

**Issue by kazhuravlev** [yujiachen-y/goaccessor#2]
It is useful when you generate an accessor for global variable like slice or map. In order to improve safety I would like to return a copy of that type. 

Example of modification global variable
```
var data = []string{"1", "2", "3"}

func Get() []string { return data }

func main() {
	ddd := Get()

	ddd[0] = "X"
	fmt.Println(Get())
}
```

So in that case I would like to specify behaviour that will copy slice (in `Get`) before return:
```
func Get()[]string{
  res := make([]string, len(data))
  copy(res, data)
  return res
}
```

**Comment by yujiachen-y** [comment]
Hi @kazhuravlev , thank you for the detailed feedback. However, this request might extend beyond the current scope of the project. Have you considered using immutable collections to achieve this level of safety? e.g. https://github.com/benbjohnson/immutable
