### ISSUE TITLE
Run go fmt before writing to file

### ISSUE THREAD

**Issue by yasv98** [yujiachen-y/goaccessor#3]
It would be good if `generator.go` could run go fmt on the code lines before writing to file. This would prevent having to add a `go:generate go fmt _filename_.go` as part of the generate commands or having the generated output fail lint checks.

I've made this change in a forked version of the repository [here](https://github.com/yasv98/goaccessor/blob/main/generator.go#L389) which could be a way to add this change. It changes the `writeFile` function to format the code lines before writing to a file.

**Comment by yujiachen-y** [comment]
@yasv98 thank you for your suggestion! I hadn't incorporated the formatting functionality because I typically format the code manually. I will address the issue soon.

**Comment by yujiachen-y** [comment]
Hi @yasv98 , #5 should resolve your issue.

**Comment by yujiachen-y** [comment]
Released https://github.com/yujiachen-y/goaccessor/releases/tag/v0.4.0

**Comment by yasv98** [comment]
Thanks!
