### ISSUE TITLE
Include version number in generated output

### ISSUE THREAD

**Issue by yasv98** [yujiachen-y/goaccessor#4]
It would be good if the goaccessor could print out the version number of the package so it can be pinned in tooldeps and help manage version control.

I've linked a PR with a possible way to do this [here](https://github.com/yujiachen-y/goaccessor/pull/9)

**Comment by yujiachen-y** [comment]
Hi @yasv98 , I appreciate your input. Currently, I use go mod for version management, along with other packages use in my projects. However, I'm open to revisiting this approach based on user feedback and evolving needs.

Beside, I'm also considering about removing arguments in the "// Code generated by \"goaccessor %s\". DO NOT EDIT." statement to make it shorter.

**Comment by yasv98** [comment]
Personally, I find this very useful for generated files. It helps manage version control and identify when there might be a drift in the version being used to generate an output. Similar to the what [protobuf](https://pkg.go.dev/google.golang.org/protobuf) has (example below):
![image](https://github.com/yujiachen-y/goaccessor/assets/112038876/23e38125-b401-4598-9899-80067dfd5e23)
